#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This script will generate a massively expanded IT glossary

network_terms = [
    ('IP Address', 'Internet Protocol Address', 'Bilgisayarının internetteki ev adresi 🏠 Tıpkı gerçek hayattaki adresin gibi, ama burada posta yerine paketler geliyor.', '192.168.1.1 - En sevdiğin router\'ın adresi. "No place like 127.0.0.1" (home sweet home)', 'IPv4\'te 4.3 milyar adres var ama dünya nüfusu 8 milyar... matematik tutmadı, IPv6 geldi 😅', 'Mülakatta sorarlar: IPv4 vs IPv6 farkı nedir? Cevap: Adres uzunluğu (32 bit vs 128 bit)'),
    ('DNS', 'Domain Name System', 'İnternetin rehberi 📖 google.com yazdığında IP adresine çeviren magic sistem.', 'google.com → 142.250.185.206', 'DNS cache zehirlenmesi = Rehbere yanlış adres yazmak gibi 😈', 'DNS port numarası? 53! Unutma bunu, çok sorarlar'),
    ('VLAN', 'Virtual Local Area Network', 'Aynı switch\'te sanal ağ bölmeleri oluşturma 🎭 Departmanları birbirinden izole etmeye yarar.', 'VLAN 10 = IT, VLAN 20 = HR, VLAN 30 = Guest. Inter-VLAN routing ile konuşturursun', 'Trunk port ile birden fazla VLAN taşırsın. 802.1Q tagging! 🏷️', 'Default VLAN numarası? VLAN 1. Asla kullanma, güvenlik riski!'),
    ('NAT', 'Network Address Translation', 'Private IP\'leri public IP\'ye çevirme sihri 🪄 Router\'ın dönüştürme makinesi.', 'Evdeki tüm cihazlar 192.168.x.x ama dışarıya tek public IP ile çıkarsınız', 'NAT olmasa herkes public IP alacaktı. IPv4 bitecekti çoktan! 💀', 'PAT (Port Address Translation) = NAT overload. Aynı public IP, farklı portlar'),
    ('Subnet Mask', 'Ağ Maskesi', 'Network\'ünün komşularını belirleyen duvar 🧱', '255.255.255.0 = /24 = 254 host', 'CIDR notation ile /24, /25, /26 yazarsın 🎯', '192.168.1.0/26 kaç host? Cevap: 62 usable host'),
    ('Gateway', 'Default Gateway', 'Mahalleden dışarıya çıkış kapısı 🚪', 'Router\'ın IP adresi genelde gateway\'dir', 'Gateway down = Mahalle karantinada 😢', 'Default gateway nedir? Cevap: Local network dışına çıkmak için kullanılan IP'),
    ('DHCP', 'Dynamic Host Configuration Protocol', 'Otomatik IP dağıtım servisi 🎰', 'DHCP olmasa her cihaza elle IP yazacaksın 💀', 'DHCP lease süresi bitince IP geri alınır 🏠', 'DHCP hangi portları kullanır? 67 (server) ve 68 (client)'),
    ('MAC Address', 'Media Access Control Address', 'Cihazının doğuştan gelen kimlik numarası 🆔', '00:1A:2B:3C:4D:5E - 6 oktetlik hex değer', 'MAC spoofing ile değiştirebilirsin 🚫', 'MAC adresi hangi OSI katmanında? Layer 2 (Data Link)'),
    ('OSI Model', '7 Katmanlı Model', 'Networkin 7 katlı döneri 🌯', 'L1: Kablolar → L7: Application', 'Please Do Not Throw Sausage Pizza Away 🍕', 'Router hangi katmanda? Layer 3. Switch? Layer 2.'),
    ('TCP', 'Transmission Control Protocol', 'İnternetin omurgası 🦴 Güvenilir veri iletimi', '3-way handshake: SYN → SYN-ACK → ACK 👋', 'TCP = Güvenilir ama yavaş 🎯', 'TCP vs UDP farkı? TCP connection-oriented'),
    ('UDP', 'User Datagram Protocol', 'Hızlı ama güvensiz protokol 🏎️ Video streaming için ideal', 'DNS, VoIP, online games UDP kullanır', 'Fire and forget! Paket gitti mi gitmedi mi umrunda değil 🤷', 'UDP neden hızlı? Connection setup yok, acknowledgment yok'),
    ('Port', 'Network Port', 'Servislerin kapı numarası 🚪 Her servis farklı port dinler', 'HTTP=80, HTTPS=443, SSH=22, RDP=3389', '65535 port var! Well-known (0-1023), Registered (1024-49151) 📊', 'FTP hangi portları kullanır? 20 (data) ve 21 (control)'),
    ('Firewall', 'Güvenlik Duvarı', 'Network\'ün kapı görevlisi 💂', 'Inbound/Outbound rules. Allow, Block, Log', 'NGFW = Uygulama bazlı kontrol 🚀', 'Stateful vs Stateless? Stateful connection\'ları hatırlar'),
    ('VPN', 'Virtual Private Network', 'İnternette gizli tünel 🕵️', 'Site-to-Site VPN = Ofisler arası', 'Split tunnel = Sadece office trafiği VPN\'den 🎯', 'IPSec vs SSL VPN farkı? IPSec L3, SSL VPN L7'),
    ('Proxy', 'Proxy Server', 'Aradaki elçi adam 🤝 İstekleri senin yerine yapar', 'Forward proxy = Client tarafı. Reverse proxy = Server tarafı', 'Squid, HAProxy popüler proxy yazılımları 📦', 'Transparent proxy = Client farkında değil. Explicit = Manuel ayar gerekir'),
    ('Load Balancer', 'Yük Dengeleyici', 'Trafiği sunuculara dengeli dağıtan akıllı kutu ⚖️', 'Round-robin, Least connections, IP hash algoritmaları', 'Layer 4 (TCP/UDP) ve Layer 7 (HTTP) load balancing var 🎭', 'Health check ile down olan servera trafik göndermez'),
    ('CDN', 'Content Delivery Network', 'Dünyanın dört bir yanına dağılmış cache sunucuları 🌍', 'Cloudflare, Akamai, AWS CloudFront popüler CDN\'ler', 'Edge location = Kullanıcıya en yakın sunucu. Latency düşer! 🚀', 'CDN ile static content\'i hızlı dağıt: JS, CSS, images'),
    ('Bandwidth', 'Bant Genişliği', 'Boru çapı gibi düşün 🚰 Ne kadar veri akabilir gösterir', '100 Mbps, 1 Gbps, 10 Gbps... Daha büyük = Daha hızlı', 'Bandwidth vs Throughput: Bandwidth teorik max, Throughput gerçek hız 📊', 'Bandwidth test için iperf kullan. Speedtest.net sadece internet için'),
    ('Latency', 'Gecikme', 'Veri gidip gelme süresi ⏱️ Ping değeri latency\'dir', 'Oyunlarda <50ms harika, <100ms iyi, >150ms lag', 'Fiber < Cable < Satellite latency sıralaması 🛰️', 'RTT (Round Trip Time) = Ping = Latency. Hepsi aynı şey'),
    ('Throughput', 'İş Hacmi', 'Gerçek veri aktarım hızı 📈 Bandwidth\'ten düşük olur', 'Bandwidth 1Gbps ama throughput 800Mbps - normal', 'Packet loss, latency, protocol overhead throughput düşürür 📉', 'iperf ile gerçek throughput ölç. Teorik bandwidth yeterli değil'),
    ('Packet Loss', 'Paket Kaybı', 'Yolda kaybolan paketler 📦 Network sorunlarının habercisi', '%1 packet loss = Kabul edilebilir. %5+ = Sorun var', 'Ping -t ile sürekli ping at, packet loss gör 🔍', 'VoIP ve video conference packet loss\'a çok hassas'),
    ('QoS', 'Quality of Service', 'Öncelikli trafik yönetimi 🎯 VoIP, video önce geçer', 'DSCP marking ile paketleri önceliklendirirsin', 'VoIP packets > Email packets. QoS bunu garantiler 📞', 'CoS (Class of Service) = Layer 2. QoS = Layer 3'),
    ('ARP', 'Address Resolution Protocol', 'IP\'den MAC bulma protokolü 🔍', 'IP biliyorsun ama MAC lazım? ARP broadcast! ', 'ARP cache poisoning = MITM attack\'ın temel silahı 😈', 'arp -a komutu ile ARP table\'ı gör'),
    ('ICMP', 'Internet Control Message Protocol', 'Hata mesajları ve diagnostic protokolü 🚨', 'Ping ve traceroute ICMP kullanır', 'ICMP flood = Ping of Death attack 💀', 'ICMP Type 8 = Echo request (ping). Type 0 = Echo reply'),
    ('Traceroute', 'Yol İzleme', 'Paketi n hedefe nasıl gitti gösterir 🗺️', 'Her hop\'ta TTL azalır, router cevap verir', 'Windows\'ta tracert, Linux\'ta traceroute 🖥️', 'Traceroute ile bottleneck hop\'u bul'),
    ('SSH', 'Secure Shell', 'Güvenli uzak bağlantı 🔐 Telnet\'in şifreli hali', 'Port 22. ssh user@server komutu', 'SSH keys > Password. Public/private key pair kullan! 🔑', 'ssh-keygen ile key oluştur. ssh-copy-id ile servera kopyala'),
    ('FTP', 'File Transfer Protocol', 'Dosya aktarım protokolü 📁 Eski ama hala kullanılıyor', 'Port 21 (control), 20 (data). Active vs Passive mod var', 'Plain text şifre gönderir. Güvensiz! SFTP kullan 🚫', 'FileZilla popüler FTP client. WinSCP da iyi'),
    ('SFTP', 'SSH File Transfer Protocol', 'SSH üzerinden güvenli dosya transferi 🔒', 'Port 22 (SSH ile aynı). Şifreli transfer', 'SFTP > FTP her zaman. Güvenlik önemli! 🎯', 'FTPS vs SFTP: FTPS = FTP+SSL. SFTP = SSH üzerinden'),
    ('HTTP', 'Hypertext Transfer Protocol', 'Web\'in konuşma dili 🌐 Browser-server iletişimi', 'Port 80. GET, POST, PUT, DELETE metodları', 'HTTP stateless = Her istek bağımsız. Cookie ile state yönetilir 🍪', 'HTTP/1.1 vs HTTP/2 vs HTTP/3. Her biri daha hızlı'),
    ('HTTPS', 'HTTP Secure', 'Şifreli web iletişimi 🔐 SSL/TLS ile güvenli', 'Port 443. Sertifika gerektirir', 'Let\'s Encrypt ile ücretsiz SSL! Artık bahane yok 🚀', 'HTTPS everywhere! Google ranking için de gerekli'),
    ('SSL/TLS', 'Secure Sockets Layer / Transport Layer Security', 'Şifreleme protokolü 🔐 HTTPS\'in temeli', 'TLS 1.2 ve 1.3 kullan. SSL deprecated! ', 'Handshake sırasında cipher suite negotiate edilir 🤝', 'Certificate chain doğrulaması: Root CA → Intermediate → Server cert'),
    ('BGP', 'Border Gateway Protocol', 'İnternetin yönlendirme protokolü 🌍 AS\'ler arası', 'AS number ile autonomous system tanımlanır', 'BGP hijacking ile tüm internet trafiğini çalabilirsin 😱', 'iBGP (internal) vs eBGP (external)'),
    ('OSPF', 'Open Shortest Path First', 'Dinamik routing protokolü 🗺️ Link-state based', 'Area 0 = Backbone area. Diğer area\'lar buraya bağlanır', 'Dijkstra algorithm ile shortest path bulunur 🎯', 'OSPF vs EIGRP: OSPF open standard, EIGRP Cisco proprietary'),
    ('MPLS', 'Multiprotocol Label Switching', 'Label-based hızlı routing 🏷️ Service provider\'ların favorisi', 'VPN servisleri MPLS üzerinden sunulur', 'Layer 2.5 protokol! OSI model\'e sığmaz 😄', 'MPLS VPN ile site-to-site bağlantı sağlayım kurabilirsin'),
    ('SNMP', 'Simple Network Management Protocol', 'Network cihazlarını monitörleme protokolü 📊', 'Port 161/162. Agent ve Manager yapısı', 'SNMPv3 kullan! v1 ve v2c güvensiz 🔓', 'MIB (Management Information Base) = SNMP\'nin datası'),
    ('Syslog', 'System Logging Protocol', 'Log toplama protokolü 📜 Merkezi loglama', 'Port 514. UDP (hızlı) veya TCP (güvenilir)', 'Severity levels: 0=Emergency, 1=Alert, ..., 7=Debug 🚨', 'Syslog server ile tüm cihaz loglarını tek yerde topla'),
    ('NTP', 'Network Time Protocol', 'Saat senkronizasyonu ⏰ Tüm cihazlar aynı saatte', 'Port 123. Stratum seviyesi ile kaynak kalitesi belirtilir', 'Kerberos authentication için saat farkı max 5 dakika olabilir! 🕐', 'pool.ntp.org public NTP sunucuları. time.google.com da var'),
    ('RADIUS', 'Remote Authentication Dial-In User Service', 'Merkezi authentication servisi 🎫 WiFi, VPN için', 'Port 1812 (auth), 1813 (accounting)', 'FreeRADIUS açık kaynak popüler RADIUS server 🆓', 'TACACS+ vs RADIUS: TACACS+ full TCP, RADIUS UDP. TACACS+ Cisco'),
    ('VXLAN', 'Virtual Extensible LAN', 'Overlay network teknolojisi ☁️ 16 milyon VLAN!', 'VLAN limitation (4096) aşmak için. Data center için', 'Encapsulation ile Layer 2 over Layer 3 🎭', 'NSX, ACI gibi SDN çözümleri VXLAN kullanır'),
    ('SD-WAN', 'Software-Defined WAN', 'Akıllı WAN yönetimi 🧠 Trafik otomatik optimize', 'Multiple ISP + Dynamic path selection = Always on! ', 'MPLS\'den ucuz, daha esnek. Yeni nesil WAN 🚀', 'Application-aware routing ile kritik app\'ler en iyi path\'ten gider'),
]

print(f"Network: {len(network_terms)} terms")
print("Glossary expansion script ready!")
