import { useState } from 'react'
import { Shield, Download, Copy, Check, Plus, Trash2 } from 'lucide-react'

const FirewallRuleGenerator = () => {
  const [rules, setRules] = useState([{
    name: '',
    action: 'Allow',
    direction: 'Inbound',
    protocol: 'TCP',
    port: '',
    program: '',
    remoteAddress: 'Any',
    profile: 'Domain,Private,Public'
  }])
  const [copied, setCopied] = useState(false)

  const addRule = () => setRules([...rules, { name: '', action: 'Allow', direction: 'Inbound', protocol: 'TCP', port: '', program: '', remoteAddress: 'Any', profile: 'Domain,Private,Public' }])
  const removeRule = (index) => setRules(rules.filter((_, i) => i !== index))
  const updateRule = (index, field, value) => {
    const newRules = [...rules]
    newRules[index][field] = value
    setRules(newRules)
  }

  const generateScript = () => {
    const validRules = rules.filter(r => r.name && (r.port || r.program))

    const script = [
      '# Windows Firewall Rules Generator',
      '# Generated by Cemal Demirci Portfolio Tools',
      '# Run as Administrator',
      '',
      '$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)',
      'if (-not $isAdmin) {',
      '    Write-Host "Please run as Administrator!" -ForegroundColor Red',
      '    pause',
      '    exit',
      '}',
      '',
      'Write-Host "Creating firewall rules..." -ForegroundColor Green',
      ''
    ]

    validRules.forEach((rule, i) => {
      script.push(`# Rule ${i + 1}: ${rule.name}`)
      script.push('try {')

      let cmd = `    New-NetFirewallRule -DisplayName "${rule.name}" `
      cmd += `-Direction ${rule.direction} `
      cmd += `-Action ${rule.action} `
      cmd += `-Protocol ${rule.protocol} `

      if (rule.port) cmd += `-LocalPort ${rule.port} `
      if (rule.program) cmd += `-Program "${rule.program}" `
      if (rule.remoteAddress !== 'Any') cmd += `-RemoteAddress ${rule.remoteAddress} `
      cmd += `-Profile ${rule.profile} `
      cmd += `-Enabled True`

      script.push(cmd)
      script.push(`    Write-Host "✓ Created rule: ${rule.name}" -ForegroundColor Green`)
      script.push('} catch {')
      script.push(`    Write-Host "✗ Failed: $_" -ForegroundColor Red`)
      script.push('}')
      script.push('')
    })

    script.push('Write-Host "Firewall rules created!" -ForegroundColor Green')
    script.push('pause')
    return script.join('\n')
  }

  const copyScript = () => {
    navigator.clipboard.writeText(generateScript())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white flex items-center justify-center gap-2">
          <Shield className="w-8 h-8" />
          Firewall Rule Generator
        </h1>
        <p className="text-gray-400">Generate Windows Firewall rules script</p>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <div className="flex justify-between items-center">
          <h3 className="font-semibold text-white">Rules ({rules.length})</h3>
          <button onClick={addRule} className="btn-primary flex items-center gap-2">
            <Plus className="w-5 h-5" />
            Add Rule
          </button>
        </div>

        <div className="space-y-3 max-h-[500px] overflow-y-auto">
          {rules.map((rule, index) => (
            <div key={index} className="p-4 bg-gray-50 bg-gray-700/50 rounded-lg space-y-3">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <input
                  type="text"
                  value={rule.name}
                  onChange={(e) => updateRule(index, 'name', e.target.value)}
                  placeholder="Rule Name*"
                  className="input-field text-sm bg-gray-700 border-gray-600 text-white"
                />
                <select
                  value={rule.action}
                  onChange={(e) => updateRule(index, 'action', e.target.value)}
                  className="input-field text-sm bg-gray-700 border-gray-600 text-white"
                >
                  <option>Allow</option>
                  <option>Block</option>
                </select>
                <select
                  value={rule.direction}
                  onChange={(e) => updateRule(index, 'direction', e.target.value)}
                  className="input-field text-sm bg-gray-700 border-gray-600 text-white"
                >
                  <option>Inbound</option>
                  <option>Outbound</option>
                </select>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <select
                  value={rule.protocol}
                  onChange={(e) => updateRule(index, 'protocol', e.target.value)}
                  className="input-field text-sm bg-gray-700 border-gray-600 text-white"
                >
                  <option>TCP</option>
                  <option>UDP</option>
                  <option>Any</option>
                </select>
                <input
                  type="text"
                  value={rule.port}
                  onChange={(e) => updateRule(index, 'port', e.target.value)}
                  placeholder="Port (e.g., 80, 443, 8000-8080)"
                  className="input-field text-sm bg-gray-700 border-gray-600 text-white"
                />
                <input
                  type="text"
                  value={rule.remoteAddress}
                  onChange={(e) => updateRule(index, 'remoteAddress', e.target.value)}
                  placeholder="Remote IP (Any, 192.168.1.0/24)"
                  className="input-field text-sm bg-gray-700 border-gray-600 text-white"
                />
              </div>

              <div className="flex gap-3">
                <input
                  type="text"
                  value={rule.program}
                  onChange={(e) => updateRule(index, 'program', e.target.value)}
                  placeholder="Program Path (optional)"
                  className="input-field flex-1 text-sm bg-gray-700 border-gray-600 text-white"
                />
                <button
                  onClick={() => removeRule(index)}
                  className="px-3 py-2 bg-red-900/30 text-red-400 rounded hover:bg-red-200"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))}
        </div>

        <button onClick={copyScript} className="btn-primary w-full flex items-center justify-center gap-2">
          {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
          {copied ? 'Copied!' : 'Copy Script'}
        </button>
      </div>
    </div>
  )
}

export default FirewallRuleGenerator
