import { useState } from 'react'
import { FileText, Download, Copy, Check, Plus, Trash2 } from 'lucide-react'

const HostsFileManager = () => {
  const [entries, setEntries] = useState([{ ip: '', hostname: '', comment: '' }])
  const [action, setAction] = useState('add') // add, remove, backup
  const [copied, setCopied] = useState(false)

  const addEntry = () => setEntries([...entries, { ip: '', hostname: '', comment: '' }])
  const removeEntry = (index) => setEntries(entries.filter((_, i) => i !== index))
  const updateEntry = (index, field, value) => {
    const newEntries = [...entries]
    newEntries[index][field] = value
    setEntries(newEntries)
  }

  const adBlockingList = [
    { ip: '0.0.0.0', hostname: 'ads.google.com', comment: 'Block Google Ads' },
    { ip: '0.0.0.0', hostname: 'doubleclick.net', comment: 'Block DoubleClick' },
    { ip: '0.0.0.0', hostname: 'facebook.com', comment: 'Block Facebook' },
    { ip: '0.0.0.0', hostname: 'www.facebook.com', comment: 'Block Facebook WWW' }
  ]

  const generateScript = () => {
    if (action === 'backup') {
      return `# Backup Hosts File
$hostsPath = "$env:SystemRoot\\System32\\drivers\\etc\\hosts"
$backupPath = "$env:UserProfile\\Desktop\\hosts_backup_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt"

Copy-Item -Path $hostsPath -Destination $backupPath -Force
Write-Host "Hosts file backed up to: $backupPath" -ForegroundColor Green
pause`
    }

    const validEntries = entries.filter(e => e.ip && e.hostname)
    const hostsPath = '$env:SystemRoot\\System32\\drivers\\etc\\hosts'

    const script = [
      '# Hosts File Manager Script',
      '# Generated by Cemal Demirci Portfolio Tools',
      '# Run as Administrator',
      '',
      '$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)',
      'if (-not $isAdmin) {',
      '    Write-Host "Please run as Administrator!" -ForegroundColor Red',
      '    pause',
      '    exit',
      '}',
      '',
      `$hostsPath = ${hostsPath}`,
      '',
      '# Backup current hosts file',
      '$backupPath = "$env:UserProfile\\Desktop\\hosts_backup_$(Get-Date -Format \'yyyyMMdd_HHmmss\').txt"',
      'Copy-Item -Path $hostsPath -Destination $backupPath',
      'Write-Host "Backup created: $backupPath" -ForegroundColor Cyan',
      ''
    ]

    if (action === 'add') {
      script.push('# Add entries to hosts file')
      script.push('$entriesToAdd = @(')
      validEntries.forEach(entry => {
        const comment = entry.comment ? ` # ${entry.comment}` : ''
        script.push(`    "${entry.ip}    ${entry.hostname}${comment}"`)
      })
      script.push(')')
      script.push('')
      script.push('foreach ($entry in $entriesToAdd) {')
      script.push('    Add-Content -Path $hostsPath -Value $entry')
      script.push('    Write-Host "Added: $entry" -ForegroundColor Green')
      script.push('}')
    } else if (action === 'remove') {
      script.push('# Remove entries from hosts file')
      script.push('$content = Get-Content -Path $hostsPath')
      script.push('$newContent = $content | Where-Object {')
      validEntries.forEach((entry, i) => {
        script.push(`    $_ -notmatch "${entry.hostname}"${i < validEntries.length - 1 ? ' -and' : ''}`)
      })
      script.push('}')
      script.push('Set-Content -Path $hostsPath -Value $newContent')
      script.push('Write-Host "Entries removed" -ForegroundColor Green')
    }

    script.push('')
    script.push('# Flush DNS cache')
    script.push('ipconfig /flushdns')
    script.push('Write-Host "DNS cache flushed" -ForegroundColor Cyan')
    script.push('')
    script.push('Write-Host "Hosts file updated successfully!" -ForegroundColor Green')
    script.push('pause')

    return script.join('\n')
  }

  const loadAdBlocking = () => {
    setEntries(adBlockingList)
  }

  const copyScript = () => {
    navigator.clipboard.writeText(generateScript())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white flex items-center justify-center gap-2">
          <FileText className="w-8 h-8" />
          Hosts File Manager
        </h1>
        <p className="text-gray-400">Manage Windows hosts file entries</p>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={() => setAction('add')}
            className={`px-4 py-2 rounded-lg font-medium ${action === 'add' ? 'bg-primary-500 text-white' : 'bg-gray-700 text-gray-300'}`}
          >
            Add Entries
          </button>
          <button
            onClick={() => setAction('remove')}
            className={`px-4 py-2 rounded-lg font-medium ${action === 'remove' ? 'bg-primary-500 text-white' : 'bg-gray-700 text-gray-300'}`}
          >
            Remove Entries
          </button>
          <button
            onClick={() => setAction('backup')}
            className={`px-4 py-2 rounded-lg font-medium ${action === 'backup' ? 'bg-primary-500 text-white' : 'bg-gray-700 text-gray-300'}`}
          >
            Backup Only
          </button>
          {action === 'add' && (
            <button
              onClick={loadAdBlocking}
              className="px-4 py-2 rounded-lg font-medium bg-red-900/30 text-red-400 hover:bg-red-200"
            >
              Load Ad-Blocking List
            </button>
          )}
        </div>

        {action !== 'backup' && (
          <div>
            <div className="flex justify-between items-center mb-3">
              <h3 className="font-semibold text-white">Hosts Entries</h3>
              <button onClick={addEntry} className="btn-primary flex items-center gap-2">
                <Plus className="w-5 h-5" />
                Add Entry
              </button>
            </div>

            <div className="space-y-2">
              {entries.map((entry, index) => (
                <div key={index} className="grid grid-cols-1 md:grid-cols-12 gap-2">
                  <input
                    type="text"
                    value={entry.ip}
                    onChange={(e) => updateEntry(index, 'ip', e.target.value)}
                    placeholder="IP Address"
                    className="input-field text-sm md:col-span-3 bg-gray-700 border-gray-600 text-white"
                  />
                  <input
                    type="text"
                    value={entry.hostname}
                    onChange={(e) => updateEntry(index, 'hostname', e.target.value)}
                    placeholder="Hostname/Domain"
                    className="input-field text-sm md:col-span-4 bg-gray-700 border-gray-600 text-white"
                  />
                  <input
                    type="text"
                    value={entry.comment}
                    onChange={(e) => updateEntry(index, 'comment', e.target.value)}
                    placeholder="Comment (optional)"
                    className="input-field text-sm md:col-span-4 bg-gray-700 border-gray-600 text-white"
                  />
                  <button
                    onClick={() => removeEntry(index)}
                    className="px-3 py-2 bg-red-900/30 text-red-400 rounded hover:bg-red-200 md:col-span-1"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        <button onClick={copyScript} className="btn-primary w-full flex items-center justify-center gap-2">
          {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
          {copied ? 'Copied!' : 'Copy Script'}
        </button>
      </div>

      <div className="bg-blue-900/20 border border-blue-800 rounded-lg p-4">
        <p className="text-sm text-blue-300">
          <strong>Tip:</strong> Hosts file location: <code>C:\Windows\System32\drivers\etc\hosts</code>
          <br />Use 0.0.0.0 to block domains, or specific IPs to redirect.
        </p>
      </div>
    </div>
  )
}

export default HostsFileManager
