import { useState } from 'react'
import { RefreshCw, Download, Copy, Check } from 'lucide-react'

const NetworkReset = () => {
  const [options, setOptions] = useState({
    flushDNS: true,
    resetWinsock: true,
    resetTCPIP: true,
    renewIP: true,
    resetFirewall: false,
    resetProxy: true,
    clearARP: true,
    resetNetBIOS: false
  })
  const [copied, setCopied] = useState(false)

  const generateScript = () => {
    const script = [
      '# Network Reset & Repair Script',
      '# Generated by Cemal Demirci Portfolio Tools',
      '# Run as Administrator',
      '',
      '$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)',
      'if (-not $isAdmin) {',
      '    Write-Host "Please run as Administrator!" -ForegroundColor Red',
      '    pause',
      '    exit',
      '}',
      '',
      'Write-Host "Starting Network Reset..." -ForegroundColor Green',
      ''
    ]

    if (options.flushDNS) {
      script.push('Write-Host "Flushing DNS cache..." -ForegroundColor Cyan')
      script.push('ipconfig /flushdns')
      script.push('')
    }

    if (options.resetWinsock) {
      script.push('Write-Host "Resetting Winsock catalog..." -ForegroundColor Cyan')
      script.push('netsh winsock reset')
      script.push('')
    }

    if (options.resetTCPIP) {
      script.push('Write-Host "Resetting TCP/IP stack..." -ForegroundColor Cyan')
      script.push('netsh int ip reset')
      script.push('netsh int ipv4 reset')
      script.push('netsh int ipv6 reset')
      script.push('')
    }

    if (options.renewIP) {
      script.push('Write-Host "Releasing and renewing IP..." -ForegroundColor Cyan')
      script.push('ipconfig /release')
      script.push('ipconfig /renew')
      script.push('')
    }

    if (options.resetFirewall) {
      script.push('Write-Host "Resetting Windows Firewall..." -ForegroundColor Cyan')
      script.push('netsh advfirewall reset')
      script.push('')
    }

    if (options.resetProxy) {
      script.push('Write-Host "Resetting proxy settings..." -ForegroundColor Cyan')
      script.push('netsh winhttp reset proxy')
      script.push('')
    }

    if (options.clearARP) {
      script.push('Write-Host "Clearing ARP cache..." -ForegroundColor Cyan')
      script.push('arp -d *')
      script.push('')
    }

    if (options.resetNetBIOS) {
      script.push('Write-Host "Resetting NetBIOS..." -ForegroundColor Cyan')
      script.push('nbtstat -R')
      script.push('nbtstat -RR')
      script.push('')
    }

    script.push('Write-Host "Network reset completed!" -ForegroundColor Green')
    script.push('Write-Host "Please restart your computer for changes to take effect." -ForegroundColor Yellow')
    script.push('pause')

    return script.join('\n')
  }

  const copyScript = () => {
    navigator.clipboard.writeText(generateScript())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadScript = () => {
    const blob = new Blob([generateScript()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'NetworkReset.ps1'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white flex items-center justify-center gap-2">
          <RefreshCw className="w-8 h-8" />
          Network Reset & Repair
        </h1>
        <p className="text-gray-600 dark:text-gray-400">Fix common network connectivity issues</p>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700 space-y-4">
        <h3 className="font-semibold text-gray-900 dark:text-white">Select Operations</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {Object.entries({
            flushDNS: 'Flush DNS Cache',
            resetWinsock: 'Reset Winsock Catalog',
            resetTCPIP: 'Reset TCP/IP Stack',
            renewIP: 'Release & Renew IP',
            resetFirewall: 'Reset Windows Firewall',
            resetProxy: 'Reset Proxy Settings',
            clearARP: 'Clear ARP Cache',
            resetNetBIOS: 'Reset NetBIOS'
          }).map(([key, label]) => (
            <label key={key} className="flex items-center gap-2 p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700">
              <input
                type="checkbox"
                checked={options[key]}
                onChange={(e) => setOptions({...options, [key]: e.target.checked})}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">{label}</span>
            </label>
          ))}
        </div>

        <div className="flex gap-3 pt-4">
          <button onClick={copyScript} className="btn-primary flex-1 flex items-center justify-center gap-2">
            {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
            {copied ? 'Copied!' : 'Copy Script'}
          </button>
          <button onClick={downloadScript} className="btn-primary flex-1 flex items-center justify-center gap-2">
            <Download className="w-5 h-5" />
            Download .ps1
          </button>
        </div>
      </div>

      <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
        <p className="text-sm text-yellow-800 dark:text-yellow-300">
          <strong>Warning:</strong> Some operations require a system restart. Save your work before running this script.
        </p>
      </div>
    </div>
  )
}

export default NetworkReset
