import { useState } from 'react'
import { Copy, Check, Download } from 'lucide-react'

const BloatwareRemover = () => {
  const [copied, setCopied] = useState(false)
  const [selectedApps, setSelectedApps] = useState([])

  const bloatwareApps = [
    { name: 'Microsoft.3DBuilder', display: '3D Builder' },
    { name: 'Microsoft.BingWeather', display: 'Bing Weather' },
    { name: 'Microsoft.GetHelp', display: 'Get Help' },
    { name: 'Microsoft.Getstarted', display: 'Get Started' },
    { name: 'Microsoft.MicrosoftOfficeHub', display: 'Office Hub' },
    { name: 'Microsoft.MicrosoftSolitaireCollection', display: 'Microsoft Solitaire' },
    { name: 'Microsoft.People', display: 'People' },
    { name: 'Microsoft.SkypeApp', display: 'Skype' },
    { name: 'Microsoft.WindowsAlarms', display: 'Alarms & Clock' },
    { name: 'Microsoft.WindowsCamera', display: 'Camera' },
    { name: 'Microsoft.WindowsMaps', display: 'Maps' },
    { name: 'Microsoft.WindowsSoundRecorder', display: 'Voice Recorder' },
    { name: 'Microsoft.Xbox.TCUI', display: 'Xbox TCUI' },
    { name: 'Microsoft.XboxApp', display: 'Xbox App' },
    { name: 'Microsoft.XboxGameOverlay', display: 'Xbox Game Overlay' },
    { name: 'Microsoft.XboxGamingOverlay', display: 'Xbox Gaming Overlay' },
    { name: 'Microsoft.XboxIdentityProvider', display: 'Xbox Identity Provider' },
    { name: 'Microsoft.XboxSpeechToTextOverlay', display: 'Xbox Speech To Text' },
    { name: 'Microsoft.YourPhone', display: 'Your Phone' },
    { name: 'Microsoft.ZuneMusic', display: 'Groove Music' },
    { name: 'Microsoft.ZuneVideo', display: 'Movies & TV' }
  ]

  const generateScript = () => {
    let script = `# Windows Bloatware Removal Script\n# Generated by Cemal Demirci Portfolio Tools\n# Run as Administrator\n\n`
    script += `Write-Host "Starting bloatware removal..." -ForegroundColor Cyan\n\n`

    selectedApps.forEach(app => {
      script += `# Remove ${app.display}\nGet-AppxPackage ${app.name} | Remove-AppxPackage -ErrorAction SilentlyContinue\nWrite-Host "${app.display} removed" -ForegroundColor Green\n\n`
    })

    script += `Write-Host "Bloatware removal completed!" -ForegroundColor Cyan\nWrite-Host "Please restart your computer for changes to take effect." -ForegroundColor Yellow\n`
    return script
  }

  const copyScript = () => {
    const script = generateScript()
    navigator.clipboard.writeText(script)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadScript = () => {
    const script = generateScript()
    const blob = new Blob([script], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'remove-bloatware.ps1'
    a.click()
    URL.revokeObjectURL(url)
  }

  const toggleApp = (app) => {
    setSelectedApps(prev =>
      prev.some(a => a.name === app.name)
        ? prev.filter(a => a.name !== app.name)
        : [...prev, app]
    )
  }

  const selectAll = () => setSelectedApps([...bloatwareApps])
  const clearAll = () => setSelectedApps([])

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white">Windows Bloatware Remover</h1>
        <p className="text-gray-400">Generate PowerShell script to remove unwanted Windows apps</p>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <div className="flex justify-between items-center">
          <h3 className="font-semibold text-white">Select Apps to Remove ({selectedApps.length})</h3>
          <div className="flex gap-2">
            <button onClick={selectAll} className="text-sm text-primary-400 hover:underline">
              Select All
            </button>
            <span className="text-gray-400">|</span>
            <button onClick={clearAll} className="text-sm text-gray-400 hover:underline">
              Clear All
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-96 overflow-y-auto p-2">
          {bloatwareApps.map((app) => (
            <label
              key={app.name}
              className="flex items-center space-x-2 cursor-pointer p-2 rounded hover:hover:bg-gray-700/50"
            >
              <input
                type="checkbox"
                checked={selectedApps.some(a => a.name === app.name)}
                onChange={() => toggleApp(app)}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-white">{app.display}</span>
            </label>
          ))}
        </div>

        {selectedApps.length > 0 && (
          <div className="space-y-3 pt-4 border-t border-gray-700">
            <div className="flex gap-2">
              <button onClick={copyScript} className="btn-primary flex-1 flex items-center justify-center gap-2">
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy Script'}
              </button>
              <button onClick={downloadScript} className="btn-secondary flex items-center gap-2">
                <Download className="w-4 h-4" />
                Download .ps1
              </button>
            </div>

            <div className="p-4 bg-black rounded-lg overflow-x-auto max-h-64">
              <pre className="text-xs text-green-400 font-mono whitespace-pre-wrap">{generateScript()}</pre>
            </div>
          </div>
        )}
      </div>

      <div className="bg-red-900/30 border border-red-800 rounded-lg p-4">
        <h3 className="font-semibold text-red-300 mb-2">⚠️ Important Warnings</h3>
        <ul className="text-sm text-red-400 space-y-1 list-disc list-inside">
          <li>Create a system restore point before running</li>
          <li>Some apps may be reinstalled after Windows updates</li>
          <li>Removing certain apps may affect Windows functionality</li>
          <li>Run PowerShell as Administrator</li>
          <li>Test on a non-production machine first</li>
        </ul>
      </div>

      <div className="bg-blue-900/30 border border-blue-800 rounded-lg p-4">
        <h3 className="font-semibold text-blue-300 mb-2">How to Use</h3>
        <ol className="text-sm text-blue-400 space-y-1 list-decimal list-inside">
          <li>Select the apps you want to remove</li>
          <li>Copy or download the generated PowerShell script</li>
          <li>Open PowerShell as Administrator</li>
          <li>Run the script</li>
          <li>Restart your computer</li>
        </ol>
      </div>
    </div>
  )
}

export default BloatwareRemover
