import { useState } from 'react'
import { Gamepad2, Download, Copy, Check } from 'lucide-react'

const GamingOptimizer = () => {
  const [selected, setSelected] = useState({
    gameMode: true,
    highPerformance: true,
    disableFullscreenOpt: true,
    disableGameBar: false,
    gpuScheduling: true,
    priorityBoost: true,
    disableNagle: false,
    disableHPET: false,
    reduceMTU: false
  })
  const [copied, setCopied] = useState(false)

  const optimizations = [
    {
      id: 'gameMode',
      name: 'Enable Game Mode',
      description: 'Windows Game Mode optimizes PC for gaming',
      script: 'Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\GameBar" -Name "AllowAutoGameMode" -Value 1'
    },
    {
      id: 'highPerformance',
      name: 'High Performance Power Plan',
      description: 'Set power plan to maximum performance',
      script: 'powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'
    },
    {
      id: 'disableFullscreenOpt',
      name: 'Disable Fullscreen Optimizations',
      description: 'Can improve FPS in some games',
      script: `$games = Get-ChildItem -Path "C:\\Program Files", "C:\\Program Files (x86)" -Recurse -Filter "*.exe" -ErrorAction SilentlyContinue
foreach ($game in $games) {
    $bytes = [System.IO.File]::ReadAllBytes($game.FullName)
    # Set DISABLEFULLSCREENOPTIMIZATIONS compatibility flag
    Write-Host "Processing: $($game.Name)"
}`
    },
    {
      id: 'disableGameBar',
      name: 'Disable Xbox Game Bar',
      description: 'Reduces background processes',
      script: `Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR" -Name "AppCaptureEnabled" -Value 0
Set-ItemProperty -Path "HKCU:\\System\\GameConfigStore" -Name "GameDVR_Enabled" -Value 0`
    },
    {
      id: 'gpuScheduling',
      name: 'Hardware-Accelerated GPU Scheduling',
      description: 'Reduce latency and improve performance (Windows 10 2004+)',
      script: 'Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers" -Name "HwSchMode" -Value 2'
    },
    {
      id: 'priorityBoost',
      name: 'CPU Priority for Games',
      description: 'Give higher CPU priority to game processes',
      script: `# This will set priority for currently running game - run while game is active
$gameName = "YourGame.exe"  # Replace with your game's exe name
$process = Get-Process $gameName -ErrorAction SilentlyContinue
if ($process) {
    $process.PriorityClass = "High"
    Write-Host "Priority set to High for $gameName"
}`
    },
    {
      id: 'disableNagle',
      name: 'Disable Nagle\'s Algorithm',
      description: 'Reduces network latency for online games',
      script: `$adapters = Get-NetAdapter | Where-Object {$_.Status -eq "Up"}
foreach ($adapter in $adapters) {
    Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\$($adapter.InterfaceGuid)" -Name "TcpAckFrequency" -Value 1
    Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\$($adapter.InterfaceGuid)" -Name "TCPNoDelay" -Value 1
}`
    },
    {
      id: 'disableHPET',
      name: 'Disable HPET',
      description: 'Can improve frame timing in some systems',
      script: 'bcdedit /deletevalue useplatformclock'
    },
    {
      id: 'reduceMTU',
      name: 'Optimize Network MTU',
      description: 'Optimize Maximum Transmission Unit for gaming',
      script: `$adapter = Get-NetAdapter | Where-Object {$_.Status -eq "Up"} | Select-Object -First 1
netsh interface ipv4 set subinterface "$($adapter.Name)" mtu=1492 store=persistent`
    }
  ]

  const toggleOption = (id) => {
    setSelected(prev => ({ ...prev, [id]: !prev[id] }))
  }

  const generateScript = () => {
    const scriptLines = [
      '# Gaming Performance Optimizer Script',
      '# Generated by Cemal Demirci Portfolio Tools',
      '# Run as Administrator',
      '',
      '# Check for admin rights',
      '$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)',
      'if (-not $isAdmin) {',
      '    Write-Host "Please run as Administrator!" -ForegroundColor Red',
      '    pause',
      '    exit',
      '}',
      '',
      'Write-Host "Applying Gaming Optimizations..." -ForegroundColor Green',
      ''
    ]

    optimizations.forEach(opt => {
      if (selected[opt.id]) {
        scriptLines.push(`# ${opt.name}`)
        scriptLines.push(`Write-Host "Applying: ${opt.name}" -ForegroundColor Cyan`)
        scriptLines.push(opt.script)
        scriptLines.push('')
      }
    })

    scriptLines.push('Write-Host "Optimizations applied! Restart your PC for all changes to take effect." -ForegroundColor Green')
    scriptLines.push('pause')

    return scriptLines.join('\n')
  }

  const copyScript = () => {
    const script = generateScript()
    navigator.clipboard.writeText(script)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadScript = () => {
    const script = generateScript()
    const blob = new Blob([script], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'GamingOptimizer.ps1'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const selectedCount = Object.values(selected).filter(Boolean).length

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white flex items-center justify-center gap-2">
          <Gamepad2 className="w-8 h-8" />
          Gaming Performance Optimizer
        </h1>
        <p className="text-gray-400">
          Generate PowerShell script to optimize Windows for gaming
        </p>
      </div>

      <div className="bg-yellow-900/20 border border-yellow-800 rounded-lg p-4">
        <p className="text-sm text-yellow-300">
          <strong>Warning:</strong> These optimizations modify system settings. Create a system restore point before running the script. Always run PowerShell as Administrator.
        </p>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-white">
            Select Optimizations ({selectedCount} selected)
          </h3>
          <div className="flex gap-2">
            <button
              onClick={() => setSelected(Object.keys(selected).reduce((acc, key) => ({ ...acc, [key]: true }), {}))}
              className="text-sm px-3 py-1 bg-primary-900/30 text-primary-300 rounded hover:hover:bg-primary-900/50"
            >
              Select All
            </button>
            <button
              onClick={() => setSelected(Object.keys(selected).reduce((acc, key) => ({ ...acc, [key]: false }), {}))}
              className="text-sm px-3 py-1 bg-gray-700 text-gray-300 rounded hover:hover:bg-gray-600"
            >
              Deselect All
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-3">
          {optimizations.map(opt => (
            <label
              key={opt.id}
              className={`flex items-start gap-3 p-4 rounded-lg border-2 cursor-pointer transition-colors ${
                selected[opt.id]
                  ? 'border-primary-500 bg-primary-900/20'
                  : 'border-gray-700 hover:hover:border-gray-600'
              }`}
            >
              <input
                type="checkbox"
                checked={selected[opt.id]}
                onChange={() => toggleOption(opt.id)}
                className="mt-1 w-5 h-5 text-primary-600 rounded focus:ring-primary-500"
              />
              <div className="flex-1">
                <div className="font-semibold text-white">{opt.name}</div>
                <div className="text-sm text-gray-400 mt-1">{opt.description}</div>
              </div>
            </label>
          ))}
        </div>

        <div className="flex gap-3 pt-4">
          <button
            onClick={copyScript}
            disabled={selectedCount === 0}
            className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
            {copied ? 'Copied!' : 'Copy Script'}
          </button>
          <button
            onClick={downloadScript}
            disabled={selectedCount === 0}
            className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
          >
            <Download className="w-5 h-5" />
            Download .ps1
          </button>
        </div>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
        <h3 className="font-semibold text-white mb-3">How to Use</h3>
        <ol className="list-decimal list-inside space-y-2 text-sm text-gray-400">
          <li>Create a System Restore Point before making changes</li>
          <li>Select the optimizations you want to apply</li>
          <li>Download or copy the generated PowerShell script</li>
          <li>Right-click PowerShell and select "Run as Administrator"</li>
          <li>Execute the script and restart your PC</li>
          <li>Test your games - you can revert using System Restore if needed</li>
        </ol>
      </div>
    </div>
  )
}

export default GamingOptimizer
