import { useState } from 'react'
import { Copy, Check, Download } from 'lucide-react'

const PowerManagement = () => {
  const [copied, setCopied] = useState(false)
  const [selectedOptions, setSelectedOptions] = useState({
    hibernation: false,
    fastStartup: false,
    sleepStudy: false,
    powerThrottling: false,
    usbPower: false
  })

  const generateScript = () => {
    let script = `# Windows Power Management Script\n# Generated by Cemal Demirci Portfolio Tools\n# Run as Administrator\n\n`

    if (selectedOptions.hibernation) {
      script += `# Disable Hibernation\npowercfg /hibernate off\nWrite-Host "Hibernation disabled" -ForegroundColor Green\n\n`
    }

    if (selectedOptions.fastStartup) {
      script += `# Disable Fast Startup\nreg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power" /v HiberbootEnabled /t REG_DWORD /d 0 /f\nWrite-Host "Fast Startup disabled" -ForegroundColor Green\n\n`
    }

    if (selectedOptions.sleepStudy) {
      script += `# Generate Sleep Study Report\npowercfg /sleepstudy\nWrite-Host "Sleep study report generated" -ForegroundColor Green\n\n`
    }

    if (selectedOptions.powerThrottling) {
      script += `# Disable Power Throttling\nreg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling" /v PowerThrottlingOff /t REG_DWORD /d 1 /f\nWrite-Host "Power throttling disabled" -ForegroundColor Green\n\n`
    }

    if (selectedOptions.usbPower) {
      script += `# Disable USB Selective Suspend\npowercfg /SETACVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0\npowercfg /SETDCVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0\npowercfg /SETACTIVE SCHEME_CURRENT\nWrite-Host "USB selective suspend disabled" -ForegroundColor Green\n\n`
    }

    script += `Write-Host "Power management configuration completed!" -ForegroundColor Cyan\n`
    return script
  }

  const copyScript = () => {
    const script = generateScript()
    navigator.clipboard.writeText(script)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadScript = () => {
    const script = generateScript()
    const blob = new Blob([script], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'power-management.ps1'
    a.click()
    URL.revokeObjectURL(url)
  }

  const options = [
    { key: 'hibernation', label: 'Disable Hibernation', desc: 'Disable hibernation and free up disk space' },
    { key: 'fastStartup', label: 'Disable Fast Startup', desc: 'Can help with dual-boot and update issues' },
    { key: 'sleepStudy', label: 'Generate Sleep Study', desc: 'Analyze sleep/wake issues' },
    { key: 'powerThrottling', label: 'Disable Power Throttling', desc: 'Maximum performance mode' },
    { key: 'usbPower', label: 'Disable USB Selective Suspend', desc: 'Prevent USB devices from sleeping' }
  ]

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white">Windows Power Management</h1>
        <p className="text-gray-400">Generate PowerShell scripts for power management</p>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <h3 className="font-semibold text-white">Select Options</h3>
        <div className="space-y-3">
          {options.map((option) => (
            <label key={option.key} className="flex items-start space-x-3 cursor-pointer p-3 rounded-lg hover:hover:bg-gray-700/50">
              <input
                type="checkbox"
                checked={selectedOptions[option.key]}
                onChange={(e) => setSelectedOptions({ ...selectedOptions, [option.key]: e.target.checked })}
                className="w-5 h-5 mt-0.5 text-primary-600 rounded"
              />
              <div className="flex-1">
                <div className="font-medium text-white">{option.label}</div>
                <div className="text-sm text-gray-400">{option.desc}</div>
              </div>
            </label>
          ))}
        </div>

        {Object.values(selectedOptions).some(v => v) && (
          <div className="space-y-3">
            <div className="flex gap-2">
              <button onClick={copyScript} className="btn-primary flex-1 flex items-center justify-center gap-2">
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy Script'}
              </button>
              <button onClick={downloadScript} className="btn-secondary flex items-center gap-2">
                <Download className="w-4 h-4" />
                Download .ps1
              </button>
            </div>

            <div className="p-4 bg-black rounded-lg overflow-x-auto">
              <pre className="text-sm text-green-400 font-mono whitespace-pre-wrap">{generateScript()}</pre>
            </div>
          </div>
        )}
      </div>

      <div className="bg-yellow-900/30 border border-yellow-800 rounded-lg p-4">
        <h3 className="font-semibold text-yellow-300 mb-2">⚠️ Warning</h3>
        <ul className="text-sm text-yellow-400 space-y-1 list-disc list-inside">
          <li>Run PowerShell as Administrator</li>
          <li>Create a system restore point before running</li>
          <li>Test on non-production systems first</li>
          <li>Some changes require system restart</li>
        </ul>
      </div>
    </div>
  )
}

export default PowerManagement
