import { useState } from 'react'
import { KeyRound, Download, Copy, Check, RefreshCw } from 'lucide-react'

const ADPasswordReset = () => {
  const [users, setUsers] = useState([''])
  const [settings, setSettings] = useState({
    newPassword: 'Welcome2024!',
    randomPassword: false,
    passwordLength: 12,
    requireChange: true,
    unlockAccount: true,
    logResults: true
  })
  const [copied, setCopied] = useState(false)

  const addUser = () => setUsers([...users, ''])
  const removeUser = (index) => setUsers(users.filter((_, i) => i !== index))
  const updateUser = (index, value) => {
    const newUsers = [...users]
    newUsers[index] = value
    setUsers(newUsers)
  }

  const generateRandomPassword = () => {
    const length = settings.passwordLength
    const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*'
    let password = ''
    for (let i = 0; i < length; i++) {
      password += charset.charAt(Math.floor(Math.random() * charset.length))
    }
    // Ensure complexity
    if (!/[A-Z]/.test(password)) password = password.slice(0, -1) + 'A'
    if (!/[a-z]/.test(password)) password = password.slice(0, -1) + 'a'
    if (!/[0-9]/.test(password)) password = password.slice(0, -1) + '1'
    if (!/[!@#$%^&*]/.test(password)) password = password.slice(0, -1) + '!'
    return password
  }

  const generateScript = () => {
    const validUsers = users.filter(u => u.trim())
    if (validUsers.length === 0) return ''

    const scriptLines = [
      '# Active Directory Password Reset Script',
      '# Generated by Cemal Demirci Portfolio Tools',
      '# Run as Administrator on Domain Controller',
      '',
      'Import-Module ActiveDirectory',
      '',
      '# Check admin rights',
      '$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)',
      'if (-not $isAdmin) {',
      '    Write-Host "Please run as Administrator!" -ForegroundColor Red',
      '    pause',
      '    exit',
      '}',
      '',
      '# Results array',
      '$results = @()',
      ''
    ]

    if (settings.randomPassword) {
      scriptLines.push('# Function to generate random password')
      scriptLines.push('function Generate-RandomPassword {')
      scriptLines.push(`    param([int]$length = ${settings.passwordLength})`)
      scriptLines.push('    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"')
      scriptLines.push('    $password = -join ((1..$length) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })')
      scriptLines.push('    # Ensure complexity')
      scriptLines.push('    if ($password -notmatch "[A-Z]") { $password = $password.Substring(0, $password.Length-1) + "A" }')
      scriptLines.push('    if ($password -notmatch "[a-z]") { $password = $password.Substring(0, $password.Length-1) + "a" }')
      scriptLines.push('    if ($password -notmatch "[0-9]") { $password = $password.Substring(0, $password.Length-1) + "1" }')
      scriptLines.push('    if ($password -notmatch "[!@#$%^&*]") { $password = $password.Substring(0, $password.Length-1) + "!" }')
      scriptLines.push('    return $password')
      scriptLines.push('}')
      scriptLines.push('')
    }

    scriptLines.push('Write-Host "Starting password reset process..." -ForegroundColor Green')
    scriptLines.push('')

    validUsers.forEach((username) => {
      scriptLines.push(`# Processing: ${username}`)
      scriptLines.push('try {')
      scriptLines.push(`    $user = Get-ADUser -Identity "${username}" -Properties LockedOut`)
      scriptLines.push('    ')

      if (settings.randomPassword) {
        scriptLines.push('    $newPassword = Generate-RandomPassword')
        scriptLines.push('    $securePassword = ConvertTo-SecureString $newPassword -AsPlainText -Force')
      } else {
        scriptLines.push(`    $newPassword = "${settings.newPassword}"`)
        scriptLines.push('    $securePassword = ConvertTo-SecureString $newPassword -AsPlainText -Force')
      }

      scriptLines.push('    ')
      scriptLines.push('    # Reset password')
      scriptLines.push('    Set-ADAccountPassword -Identity $user -NewPassword $securePassword -Reset')
      scriptLines.push('    ')

      if (settings.requireChange) {
        scriptLines.push('    # Require password change at next logon')
        scriptLines.push('    Set-ADUser -Identity $user -ChangePasswordAtLogon $true')
      }

      if (settings.unlockAccount) {
        scriptLines.push('    # Unlock account if locked')
        scriptLines.push('    if ($user.LockedOut) {')
        scriptLines.push('        Unlock-ADAccount -Identity $user')
        scriptLines.push('        Write-Host "  Account unlocked" -ForegroundColor Yellow')
        scriptLines.push('    }')
      }

      scriptLines.push('    ')
      scriptLines.push(`    Write-Host "✓ Password reset successful for: ${username}" -ForegroundColor Green`)

      if (settings.randomPassword) {
        scriptLines.push('    Write-Host "  New Password: $newPassword" -ForegroundColor Cyan')
        if (settings.logResults) {
          scriptLines.push(`    $results += [PSCustomObject]@{Username="${username}"; Password=$newPassword; Status="Success"}`)
        }
      }

      scriptLines.push('} catch {')
      scriptLines.push(`    Write-Host "✗ Failed to reset password for ${username}: $_" -ForegroundColor Red`)
      if (settings.logResults) {
        scriptLines.push(`    $results += [PSCustomObject]@{Username="${username}"; Password="Failed"; Status=$_.Exception.Message}`)
      }
      scriptLines.push('}')
      scriptLines.push('')
    })

    if (settings.logResults) {
      scriptLines.push('# Export results')
      scriptLines.push('$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"')
      scriptLines.push('$logPath = ".\PasswordReset_$timestamp.csv"')
      scriptLines.push('$results | Export-Csv -Path $logPath -NoTypeInformation')
      scriptLines.push('Write-Host "Results exported to: $logPath" -ForegroundColor Cyan')
      scriptLines.push('')
    }

    scriptLines.push('Write-Host "Password reset completed!" -ForegroundColor Green')
    scriptLines.push('pause')

    return scriptLines.join('\n')
  }

  const copyScript = () => {
    const script = generateScript()
    if (script) {
      navigator.clipboard.writeText(script)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const downloadScript = () => {
    const script = generateScript()
    if (script) {
      const blob = new Blob([script], { type: 'text/plain;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'AD-PasswordReset.ps1'
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }
  }

  const validUserCount = users.filter(u => u.trim()).length

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white flex items-center justify-center gap-2">
          <KeyRound className="w-8 h-8" />
          AD Password Reset
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          Generate PowerShell script to reset AD user passwords
        </p>
      </div>

      {/* Settings */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700 space-y-4">
        <h3 className="font-semibold text-gray-900 dark:text-white">Password Settings</h3>

        <div className="space-y-4">
          <label className="flex items-center gap-2">
            <input
              type="checkbox"
              checked={settings.randomPassword}
              onChange={(e) => setSettings({...settings, randomPassword: e.target.checked})}
              className="w-4 h-4 text-primary-600 rounded"
            />
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
              Generate random passwords for each user
            </span>
          </label>

          {!settings.randomPassword ? (
            <div className="space-y-2">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                New Password (Same for all users)
              </label>
              <input
                type="text"
                value={settings.newPassword}
                onChange={(e) => setSettings({...settings, newPassword: e.target.value})}
                placeholder="Welcome2024!"
                className="input-field dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              />
            </div>
          ) : (
            <div className="space-y-2">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Password Length
              </label>
              <input
                type="number"
                min="8"
                max="32"
                value={settings.passwordLength}
                onChange={(e) => setSettings({...settings, passwordLength: parseInt(e.target.value)})}
                className="input-field dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              />
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={settings.requireChange}
                onChange={(e) => setSettings({...settings, requireChange: e.target.checked})}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Require password change</span>
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={settings.unlockAccount}
                onChange={(e) => setSettings({...settings, unlockAccount: e.target.checked})}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Unlock account</span>
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={settings.logResults}
                onChange={(e) => setSettings({...settings, logResults: e.target.checked})}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-700 dark:text-gray-300">Export results to CSV</span>
            </label>
          </div>
        </div>
      </div>

      {/* Users */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700 space-y-4">
        <div className="flex justify-between items-center">
          <h3 className="font-semibold text-gray-900 dark:text-white">
            Users ({validUserCount})
          </h3>
          <button onClick={addUser} className="btn-primary flex items-center gap-2">
            <RefreshCw className="w-5 h-5" />
            Add User
          </button>
        </div>

        <div className="space-y-2">
          {users.map((user, index) => (
            <div key={index} className="flex gap-2">
              <input
                type="text"
                value={user}
                onChange={(e) => updateUser(index, e.target.value)}
                placeholder="Username or email (e.g., jdoe or jdoe@domain.com)"
                className="input-field flex-1 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              />
              {users.length > 1 && (
                <button
                  onClick={() => removeUser(index)}
                  className="px-3 py-2 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 rounded hover:bg-red-200 dark:hover:bg-red-900/50"
                >
                  Remove
                </button>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Generate */}
      <div className="flex gap-3">
        <button
          onClick={copyScript}
          disabled={validUserCount === 0}
          className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
        >
          {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
          {copied ? 'Copied!' : 'Copy Script'}
        </button>
        <button
          onClick={downloadScript}
          disabled={validUserCount === 0}
          className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
        >
          <Download className="w-5 h-5" />
          Download .ps1
        </button>
      </div>

      <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
        <p className="text-sm text-yellow-800 dark:text-yellow-300">
          <strong>Warning:</strong> This script will reset passwords for specified users. Always inform users before resetting their passwords. Run on Domain Controller as Administrator.
        </p>
      </div>
    </div>
  )
}

export default ADPasswordReset
