import { useState } from 'react'
import { Users, Download, Copy, Check, Upload, Plus, Trash2 } from 'lucide-react'

const ADUserBulkCreator = () => {
  const [users, setUsers] = useState([
    { firstName: '', lastName: '', username: '', email: '', ou: '', password: '', department: '' }
  ])
  const [copied, setCopied] = useState(false)
  const [settings, setSettings] = useState({
    domain: 'domain.com',
    defaultPassword: 'Welcome2024!',
    requirePasswordChange: true,
    enableUser: true,
    addToGroup: '',
    emailDomain: '@domain.com'
  })

  const addUser = () => {
    setUsers([...users, { firstName: '', lastName: '', username: '', email: '', ou: '', password: '', department: '' }])
  }

  const removeUser = (index) => {
    setUsers(users.filter((_, i) => i !== index))
  }

  const updateUser = (index, field, value) => {
    const newUsers = [...users]
    newUsers[index][field] = value
    setUsers(newUsers)
  }

  const handleCSVImport = (e) => {
    const file = e.target.files[0]
    if (file) {
      const reader = new FileReader()
      reader.onload = (event) => {
        const text = event.target.result
        const lines = text.split('\n')
        const headers = lines[0].split(',').map(h => h.trim())

        const importedUsers = lines.slice(1)
          .filter(line => line.trim())
          .map(line => {
            const values = line.split(',').map(v => v.trim())
            return {
              firstName: values[0] || '',
              lastName: values[1] || '',
              username: values[2] || '',
              email: values[3] || '',
              ou: values[4] || '',
              password: values[5] || settings.defaultPassword,
              department: values[6] || ''
            }
          })

        setUsers(importedUsers)
      }
      reader.readAsText(file)
    }
  }

  const generateScript = () => {
    const validUsers = users.filter(u => u.firstName && u.lastName && u.username)

    if (validUsers.length === 0) return ''

    const scriptLines = [
      '# Active Directory Bulk User Creation Script',
      '# Generated by Cemal Demirci Portfolio Tools',
      '# Run as Administrator on Domain Controller',
      '',
      '# Import Active Directory Module',
      'Import-Module ActiveDirectory',
      '',
      '# Check if running as Administrator',
      '$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)',
      'if (-not $isAdmin) {',
      '    Write-Host "Please run as Administrator!" -ForegroundColor Red',
      '    pause',
      '    exit',
      '}',
      '',
      '# Domain Settings',
      `$domain = "${settings.domain}"`,
      `$defaultPassword = ConvertTo-SecureString "${settings.defaultPassword}" -AsPlainText -Force`,
      '',
      '# Create Users',
      'Write-Host "Creating users..." -ForegroundColor Green',
      ''
    ]

    validUsers.forEach((user, index) => {
      const displayName = `${user.firstName} ${user.lastName}`
      const sam = user.username
      const upn = `${user.username}${settings.emailDomain}`
      const email = user.email || upn
      const ou = user.ou || 'CN=Users,DC=' + settings.domain.split('.').join(',DC=')
      const userPassword = user.password || settings.defaultPassword

      scriptLines.push(`# User ${index + 1}: ${displayName}`)
      scriptLines.push('try {')
      scriptLines.push(`    New-ADUser -Name "${displayName}" \\`)
      scriptLines.push(`        -GivenName "${user.firstName}" \\`)
      scriptLines.push(`        -Surname "${user.lastName}" \\`)
      scriptLines.push(`        -SamAccountName "${sam}" \\`)
      scriptLines.push(`        -UserPrincipalName "${upn}" \\`)
      scriptLines.push(`        -EmailAddress "${email}" \\`)

      if (user.department) {
        scriptLines.push(`        -Department "${user.department}" \\`)
      }

      scriptLines.push(`        -Path "${ou}" \\`)
      scriptLines.push(`        -AccountPassword (ConvertTo-SecureString "${userPassword}" -AsPlainText -Force) \\`)
      scriptLines.push(`        -Enabled $${settings.enableUser} \\`)
      scriptLines.push(`        -ChangePasswordAtLogon $${settings.requirePasswordChange}`)

      if (settings.addToGroup) {
        scriptLines.push(`    Add-ADGroupMember -Identity "${settings.addToGroup}" -Members "${sam}"`)
      }

      scriptLines.push(`    Write-Host "✓ Created: ${displayName} (${sam})" -ForegroundColor Green`)
      scriptLines.push('} catch {')
      scriptLines.push(`    Write-Host "✗ Failed to create ${displayName}: $_" -ForegroundColor Red`)
      scriptLines.push('}')
      scriptLines.push('')
    })

    scriptLines.push('Write-Host "User creation completed!" -ForegroundColor Green')
    scriptLines.push('Write-Host "Total users processed: ' + validUsers.length + '" -ForegroundColor Cyan')
    scriptLines.push('pause')

    return scriptLines.join('\n')
  }

  const copyScript = () => {
    const script = generateScript()
    if (script) {
      navigator.clipboard.writeText(script)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const downloadScript = () => {
    const script = generateScript()
    if (script) {
      const blob = new Blob([script], { type: 'text/plain;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'AD-BulkUserCreation.ps1'
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }
  }

  const downloadCSVTemplate = () => {
    const template = 'FirstName,LastName,Username,Email,OU,Password,Department\nJohn,Doe,jdoe,jdoe@domain.com,OU=Users,Welcome2024!,IT\nJane,Smith,jsmith,jsmith@domain.com,OU=Users,Welcome2024!,HR'
    const blob = new Blob([template], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'AD-Users-Template.csv'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const validUserCount = users.filter(u => u.firstName && u.lastName && u.username).length

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white flex items-center justify-center gap-2">
          <Users className="w-8 h-8" />
          AD Bulk User Creator
        </h1>
        <p className="text-gray-400">
          Create multiple Active Directory users from CSV or manual input
        </p>
      </div>

      {/* Domain Settings */}
      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <h3 className="font-semibold text-white">Domain Settings</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">Domain</label>
            <input
              type="text"
              value={settings.domain}
              onChange={(e) => setSettings({...settings, domain: e.target.value})}
              placeholder="domain.com"
              className="input-field bg-gray-700 border-gray-600 text-white"
            />
          </div>
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">Default Password</label>
            <input
              type="text"
              value={settings.defaultPassword}
              onChange={(e) => setSettings({...settings, defaultPassword: e.target.value})}
              placeholder="Welcome2024!"
              className="input-field bg-gray-700 border-gray-600 text-white"
            />
          </div>
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">Email Domain</label>
            <input
              type="text"
              value={settings.emailDomain}
              onChange={(e) => setSettings({...settings, emailDomain: e.target.value})}
              placeholder="@domain.com"
              className="input-field bg-gray-700 border-gray-600 text-white"
            />
          </div>
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">Add to Group (Optional)</label>
            <input
              type="text"
              value={settings.addToGroup}
              onChange={(e) => setSettings({...settings, addToGroup: e.target.value})}
              placeholder="Domain Users"
              className="input-field bg-gray-700 border-gray-600 text-white"
            />
          </div>
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={settings.requirePasswordChange}
                onChange={(e) => setSettings({...settings, requirePasswordChange: e.target.checked})}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-300">Require password change</span>
            </label>
          </div>
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={settings.enableUser}
                onChange={(e) => setSettings({...settings, enableUser: e.target.checked})}
                className="w-4 h-4 text-primary-600 rounded"
              />
              <span className="text-sm text-gray-300">Enable user account</span>
            </label>
          </div>
        </div>
      </div>

      {/* CSV Import */}
      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <h3 className="font-semibold text-white">Import Users</h3>
        <div className="flex gap-3">
          <label className="btn-primary flex items-center gap-2 cursor-pointer">
            <Upload className="w-5 h-5" />
            Import CSV
            <input type="file" accept=".csv" onChange={handleCSVImport} className="hidden" />
          </label>
          <button onClick={downloadCSVTemplate} className="px-4 py-2 bg-gray-700 text-gray-300 rounded-lg hover:hover:bg-gray-600 flex items-center gap-2">
            <Download className="w-5 h-5" />
            Download CSV Template
          </button>
        </div>
      </div>

      {/* Users List */}
      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 space-y-4">
        <div className="flex justify-between items-center">
          <h3 className="font-semibold text-white">
            Users ({validUserCount} valid)
          </h3>
          <button onClick={addUser} className="btn-primary flex items-center gap-2">
            <Plus className="w-5 h-5" />
            Add User
          </button>
        </div>

        <div className="space-y-3 max-h-[400px] overflow-y-auto">
          {users.map((user, index) => (
            <div key={index} className="grid grid-cols-1 md:grid-cols-8 gap-2 p-3 bg-gray-50 bg-gray-700/50 rounded-lg">
              <input
                type="text"
                value={user.firstName}
                onChange={(e) => updateUser(index, 'firstName', e.target.value)}
                placeholder="First Name*"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <input
                type="text"
                value={user.lastName}
                onChange={(e) => updateUser(index, 'lastName', e.target.value)}
                placeholder="Last Name*"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <input
                type="text"
                value={user.username}
                onChange={(e) => updateUser(index, 'username', e.target.value)}
                placeholder="Username*"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <input
                type="email"
                value={user.email}
                onChange={(e) => updateUser(index, 'email', e.target.value)}
                placeholder="Email"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <input
                type="text"
                value={user.ou}
                onChange={(e) => updateUser(index, 'ou', e.target.value)}
                placeholder="OU Path"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <input
                type="text"
                value={user.password}
                onChange={(e) => updateUser(index, 'password', e.target.value)}
                placeholder="Password"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <input
                type="text"
                value={user.department}
                onChange={(e) => updateUser(index, 'department', e.target.value)}
                placeholder="Department"
                className="input-field text-sm bg-gray-700 border-gray-600 text-white"
              />
              <button
                onClick={() => removeUser(index)}
                className="px-3 py-2 bg-red-900/30 text-red-400 rounded hover:hover:bg-red-900/50"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Generate Script */}
      <div className="flex gap-3">
        <button
          onClick={copyScript}
          disabled={validUserCount === 0}
          className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
        >
          {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
          {copied ? 'Copied!' : 'Copy PowerShell Script'}
        </button>
        <button
          onClick={downloadScript}
          disabled={validUserCount === 0}
          className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-50"
        >
          <Download className="w-5 h-5" />
          Download .ps1 File
        </button>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700">
        <h3 className="font-semibold text-white mb-3">Usage Instructions</h3>
        <ol className="list-decimal list-inside space-y-2 text-sm text-gray-400">
          <li>Configure domain settings and default options</li>
          <li>Import users from CSV or add manually (minimum: First Name, Last Name, Username)</li>
          <li>Download or copy the generated PowerShell script</li>
          <li>Run the script on your Domain Controller as Administrator</li>
          <li>The script will create all users with specified settings</li>
        </ol>
      </div>
    </div>
  )
}

export default ADUserBulkCreator
